services:
  - type: web
    name: php-subscription-app  # Change this to your app name
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile  # Path to your Dockerfile
    buildCommand: "docker build -t php-subscription-app ."
    startCommand: "docker run -p 80:80 php-subscription-app"
